# Generated by Django 5.2.17 on 2026-08-30 02:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('city', models.CharField(default='Ташкент', max_length=40)),
                ('description', models.CharField(blank=True, default='', max_length=600)),
                ('verified', models.BooleanField(default=False, verbose_name='Документы проверены')),
                ('rating', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('emoji', models.CharField(default='🛍️', max_length=8)),
                ('color', models.CharField(default='#F5F5F5', help_text='HEX-цвет чипа, например #EDE9FF', max_length=9)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='category_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.BigIntegerField(help_text='Цена в сумах, целое число', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000000000)])),
                ('old_price', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000000000)])),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('brand', models.CharField(blank=True, default='Без бренда', max_length=40)),
                ('delivery_time', models.CharField(blank=True, default='1–2 дня', max_length=40)),
                ('is_ad', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Активный'), ('draft', 'Черновик'), ('archived', 'В архиве')], default='active', max_length=10)),
                ('views', models.PositiveIntegerField(default=0)),
                ('images', models.JSONField(blank=True, default=list, help_text='Массив URL, ≤ 8; индекс 0 — главное')),
                ('characteristics', models.JSONField(blank=True, default=dict, help_text='Объект «название → значение», ≤ 24 пар')),
                ('rating', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0, editable=False)),
                ('rating_breakdown', models.JSONField(blank=True, default=list, editable=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=80)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('pros', models.CharField(blank=True, default='', max_length=200)),
                ('cons', models.CharField(blank=True, default='', max_length=200)),
                ('verified', models.BooleanField(default=False, help_text='Есть не-отменённый заказ с этим товаром')),
                ('seller_reply', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
