# Generated by Django 5.2.17 on 2026-08-30 02:30

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('packing', 'Сборка'), ('shipping', 'В доставке'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=12)),
                ('subtotal', models.BigIntegerField(default=0, editable=False)),
                ('discount', models.BigIntegerField(default=0, editable=False)),
                ('promo_code', models.CharField(blank=True, max_length=32, null=True)),
                ('delivery_cost', models.BigIntegerField(default=0, editable=False)),
                ('total', models.BigIntegerField(default=0, editable=False)),
                ('address', models.CharField(blank=True, default='', max_length=250)),
                ('pickup_point', models.CharField(blank=True, default='', max_length=120)),
                ('delivery_method', models.CharField(choices=[('courier', 'Курьер'), ('pickup', 'Самовывоз')], default='courier', max_length=10)),
                ('payment_method', models.CharField(choices=[('card', 'Карта'), ('cash', 'Наличные'), ('installment', 'Рассрочка')], default='card', max_length=12)),
                ('comment', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('packing', 'Сборка'), ('shipping', 'В доставке'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], max_length=12)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, default='', max_length=160)),
            ],
            options={
                'verbose_name': 'Событие заказа',
                'verbose_name_plural': 'События заказов',
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('price', models.BigIntegerField()),
                ('qty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказов',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('min_subtotal', models.BigIntegerField(default=0)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
