# Generated by Django 5.2 on 2026-08-28 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Например, +998901234567', max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон может содержать только цифры, пробелы, скобки, дефис и ведущий «+».', regex='^\\+?[0-9\\s\\-()]{7,20}$')], verbose_name='Телефон'),
        ),
    ]
